version: "2"
services:
    node:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        expose:
            - "8081"
        command: "npm start"
